### PR TITLE
Some changes by updates by Sleepy and bugfixes

### PR DESCRIPTION
**Pull request by Vekseid**
Some stuff from @jdarwood007 's #1 PR:

* Support forum to wiki group mapping
* Support patched SMF 2.0 forums
* AuthManager implementation
* Split user/group update times
* Add forum user id to user options

Also some minor bugfixes.

Still haven't been able to isolate what was wrong in your patch, so I'm implementing features here on a more limited basis until it can be figured it out.

This has been tested in Elkarte and SMF 2.0, functioning in both.

### CODE REVIEW

**Comment by Vekseid** [comment]
@jdarwood007 I think all that is missing from this is your general refactor, database abstraction, and old auth compatibility.

**Comment by jdarwood007** [comment]
I haven't had time to work.  But I had my PR working on my test site.  Both SMF and MW where on the same domain though.  PHP 7.2 with MariaDB.

There is one SMF PR waiting to merge for 2.1 that fixes logouts.

**Comment by Vekseid** [comment]
It might be my php version, but it's been harder to nail down what specifically. : /

Part of the reason I'm doing this is so I can upgrade PHP cleanly in the first place.

**Comment by Vekseid** [comment]
Okay, outside of your caching edits @jdarwood007 - which I can't properly test on my system at the moment - I think this covers everything else. Postgres, Auth_SMF compat, etc.

I think what was breaking my system was your compat.

I'll merge this once I confirm Elliquiy handles the upgrade properly.

**Pull request merged**
